accelerator: null
accumulate_grad_batches: null
adafactor: false
adam_epsilon: 1.0e-08
amp_backend: native
amp_level: null
attention_dropout: null
attribute: mQG
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
benchmark: null
beta: 1.0
cache_dir: pretrained
check_val_every_n_epoch: 1
ckpt_path: null
config_name: facebook/bart-base
data_dir: /data
decoder_layerdrop: null
default_root_dir: null
detect_anomaly: false
deterministic: null
devices: null
do_predict: false
do_train: true
dropout: null
early_stopping_patience: -1
enable_checkpointing: true
enable_model_summary: true
enable_progress_bar: true
encoder_layerdrop: null
eval_batch_size: 4
eval_beams: null
eval_max_gen_length: null
fast_dev_run: false
fp16: false
fp16_opt_level: O2
freeze_embeds: false
freeze_encoder: false
fuse_num: null
gpus: 1
gradient_clip_algorithm: null
gradient_clip_val: null
ipus: null
label_smoothing: 0.0
learning_rate: 5.0e-06
limit_predict_batches: null
limit_test_batches: null
limit_train_batches: null
limit_val_batches: null
log_every_n_steps: 50
logger: true
logger_name: default
loss_n: ce_mqs
lr_scheduler: linear
max_epochs: 4
max_source_length: 512
max_steps: -1
max_target_length: 128
max_time: null
min_epochs: null
min_steps: null
model_name_or_path: facebook/bart-base
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
n_test: -1
n_train: -1
n_val: -1
num_nodes: 1
num_processes: null
num_sanity_val_steps: 2
num_workers: 16
ori_dir: /data/ftqa_data.pkl
output_dir: C:\Users\shy02\youngyanggang\baselines\mQG\src/checkpoint/mQG/output_dir/
overfit_batches: 0.0
path_or_data: data
plugins: null
precision: 32
profiler: null
reload_data: true
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: true
resume_from_checkpoint: null
save_top_k: -1
seed: 42
sortish_sampler: false
src_lang: ''
strategy: null
sync_batchnorm: false
task: summarization
test_max_target_length: 128
tgt_lang: ''
tokenizer_name: facebook/bart-base
tpu_cores: null
track_grad_norm: -1
train_batch_size: 4
type_embedding: false
val_check_interval: null
val_max_target_length: 128
val_metric: val_avg_loss
warmup_steps: 0
weight_decay: 0.0
weights_save_path: null
